package cn.tf.ecps.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-13T15:23:35.055+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.ws.ecps.tf.cn/", name = "EbWSItemService")
@XmlSeeAlso({ObjectFactory.class})
public interface EbWSItemService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "publishItem", targetNamespace = "http://service.ws.ecps.tf.cn/", className = "cn.tf.ecps.stub.PublishItem")
    @WebMethod
    @ResponseWrapper(localName = "publishItemResponse", targetNamespace = "http://service.ws.ecps.tf.cn/", className = "cn.tf.ecps.stub.PublishItemResponse")
    public java.lang.String publishItem(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
